# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=50000)),
                ('tables', models.CharField(max_length=50000)),
                ('output', models.CharField(max_length=20000)),
            ],
        ),
    ]
